### ISSUE TITLE
WhatsApp format problem

### ISSUE THREAD

**Issue by Julian-quintero** [Pustur/whatsapp-chat-parser#224]
Hey, my whatsapp text log uses this format '20/6/2017 8:28 p. m. - Michelle: test' it doesn't work since it shows:

author:"p. m. - Michelle"
date: Tue Jun 20 2017 08:28:00 GMT-0500 (hora estándar oriental)
message: "test"

**Comment by Pustur** [comment]
Hello, thanks for reporting the issue! The problem was a sneaky non breaking space in your message. I fixed the parser to allow any whitespace there.

<img width="501" alt="Screen Shot 2021-05-28 at 21 34 51" src="https://user-images.githubusercontent.com/13663338/120037650-42e98580-c002-11eb-9b44-319ab16d9a6d.png">

Should work with the new version `3.1.2`, let me know if you still have problems.
